services:
  - type: web
    name: secure-messenger-backend
    env: docker
    repo: https://github.com/Wokioki/secure-messenger
    region: frankfurt
    plan: free
    branch: main
    rootDir: server
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: REACT_APP_API_URL
        sync: false